### ISSUE TITLE
ReferenceError: jsSHA is not defined

### ISSUE THREAD

**Issue by ricick** [shephertz/App42_JAVASCRIPT_SDK#4]
I've installed the lastes version in my requirejs/angular project with bower. 

On calling `App42.initialize(key, secret);` I keep getting the error `ReferenceError: jsSHA is not defined`

The sample scripts seem to ve working fine however. What am I doing wrong?

**Comment by HimanshuSShephertz** [comment]
Hello Phil,

Please make sure you have followed all the steps mentioned in the below blog post. If you still face an issue then please share your sample project with us at support@shephertz.com. It will help us to provide better support to you. 

http://blogs.shephertz.com/2013/10/04/backend-for-building-web-apps-with-angular-js-app42-cloud-api/

Himanshu Sharma

**Comment by ricick** [comment]
The problem appears to be present if you load the SDK via requirejs async loading instead of via a script tag.

**Comment by HimanshuSShephertz** [comment]
Could you please share your sample project code with us to replicate the same at our end? Please share your sample project with us at support@shephertz.com. 

Thanks,
Himanshu Sharma

**Comment by ricick** [comment]
I created a jsfiddle here that shows the problem:

http://jsfiddle.net/67fo0nkj/1/

**Comment by HimanshuSShephertz** [comment]
We have updated the sample code which you can find from below link. Kindly upgrade the variable in your sample project and let us know if your problem get resolved. 
https://jsfiddle.net/67fo0nkj/5/

Changes : 
before: require ["shephertz"], ()->
After :  require ["shephertz"], ($)->

Code added :
this.jsSHA = $
